---
- hosts: localhost
  connection: local
  vars:
    nombre_aks: Banca_AKS_Cluster
    locacion: eastus
    resource_group: rs_gp_Banca
    username: redhat
    dns_prefix: dnsbanca
  tasks:
    - name: Crear un resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ locacion }}" 
    - name: Crear y gestionar un instacia de Azure Container Services (AKS)
      azure_rm_aks:
        name: "{{ nombre_aks }}"
        location: "{{ locacion }}"
        resource_group: "{{ resource_group }}"
        dns_prefix: "{{ dns_prefix }}"
        linux_profile:
              service_principal:
          client_id: "{{ client_id }}"
          client_secret: "{{ client_secret }}"
        agent_pool_profiles:
          - name: default
            count: 2
            vm_size: Standard_D2_v2
