---
- hosts: localhost
  connection: local
  tasks:
  - name: Crear el archivo zip
    archive:
      path: my_lambda_function/main.py
      dest: lambda.zip
      format: zip
  - name: Crear un Lambda Function
    lambda:
      name: FuncionLambdaBanca
      zip_file: lambda.zip
      region: us-east-2
      state: present
      runtime: python3.6
      role: "arn:aws:iam::020708902733:role/service-role/myFirtsLambdaApp-role-c8i5tsds"
      handler: lambda.handler
      timeout: 5
      memory_size: 128
